#!/bin/bash

source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common

echo "Stopping nginx."
if [ -f ${OPENSHIFT_RUN_DIR}/nginx.pid ];then
    kill -QUIT `cat ${OPENSHIFT_RUN_DIR}/nginx.pid`
fi

echo "Stopping PHP-fpm."
if [ -f ${OPENSHIFT_RUN_DIR}/php-fpm.pid ];then
    kill -QUIT `cat ${OPENSHIFT_RUN_DIR}/php-fpm.pid`
fi

# Always succeed, otherwise OpenShift declines to run build and start
# hooks.
exit 0
